
pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/appveyor/pr
      - status-success=Codacy/PR Quality Review
    actions:
      merge:
        method: merge
