
pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/appveyor/pr
      - status-success=Codacy Static Code Analysis
      - base=master
      - label!=work-in-progress
    actions:
      merge:
        method: merge
      delete_head_branch: {}
