sudo: required
dist: trusty

language: cpp

branches:
  only:
    - master
    - travis_test

notifications:
    on_failure: never
    on_success: never

matrix:
    include:
        - compiler: gcc
          addons:
            apt:
             packages:
               - libboost-all-dev
               - google-mock
               - g++-5
               - gcc-5
             sources:
               - ubuntu-toolchain-r-test
          # use compiler which has c++14 support
          env: 
            - COMPILER=g++-5 SHARED_BUILD=ON
            - COMPILER=g++-5 SHARED_BUILD=OFF

        - compiler: clang
          addons:
            apt:
             packages:
               - libboost-all-dev
               - google-mock
               - clang-3.6
             sources:
               - ubuntu-toolchain-r-test
               - llvm-toolchain-precise-3.6
          # use compiler which has c++14 support
          env: 
            - COMPILER=clang++-3.6 SHARED_BUILD=ON
            - COMPILER=clang++-3.6 SHARED_BUILD=OFF

before_install:
    # setup Qt 5.5 which is not in Ubuntu by default. To be removed in the future.
  - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
  - sudo apt-get -qq update
  - sudo sudo apt-get install -qq qt55base qt55svg
  - source /opt/qt55/bin/qt55-env.sh

before_script:
  # third party stuff
  - mkdir build_third_party
  - pushd build_third_party
  - CXX=$COMPILER cmake -DBUILD_OPENLIBRARY=OFF -DBUILD_EASYEXIF=ON -DBUILD_JSONCPP=ON -DINSTALL_LOCATION=/usr ../cmake/third_party/
  - sudo make
  - popd
  # OL. For some unknown reason we cannot use script above to install OL - cmake cannot find Qt5Widgets.
  - mkdir build_ol && pushd build_ol
  - git clone git://github.com/Kicer86/openlibrary.git
  - cd openlibrary
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - make
  - sudo make install
  - popd
  # photo broom
  - mkdir build && cd build
  - CXX=$COMPILER cmake -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=$SHARED_BUILD ..

script: make
