
language: cpp
sudo: required
dist: trusty

branches:
  except:
    - appveyor

addons:
  apt:
    packages:
      - libexiv2-dev
      - qt510base
      - qt510svg
      - python3
      - g++-7
      - gcc-7
      - clang-5.0
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
      - sourceline: 'ppa:beineri/opt-qt-5.10.1-trusty'

notifications:
  on_failure: never
  on_success: never

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc

  allow_failures:
    - os: osx

cache:
  directories:
    - $TRAVIS_BUILD_DIR/usr
    - $HOME/conanData           # Conan storage location

before_install:
  # setup tools for particular system
  - if [ $TRAVIS_OS_NAME == 'osx' ]; then
        brew upgrade pyenv;
        brew install qt@5.10 exiv2;
        pyenv install 3.5.2;
        pyenv global 3.5.2;
        eval "$(pyenv init -)";
        export PATH="/usr/local/opt/qt@5.10/bin:$PATH"
        export CMAKE_BIN=cmake;
        export PYTHON=python;
        sudo pip install virtualenv;
        virtualenv conan;
        source conan/bin/activate;
    else
        pyenv install 3.6.0;
        pyenv global 3.6.0;
        source /opt/qt5*/bin/qt5*-env.sh;
        wget https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.sh;
        chmod +x ./cmake-3.9.1-Linux-x86_64.sh;
        ./cmake-3.9.1-Linux-x86_64.sh --prefix=$TRAVIS_BUILD_DIR/usr --exclude-subdir --skip-license;
        export CMAKE_BIN=$TRAVIS_BUILD_DIR/usr/bin/cmake;
        export PYTHON=`which python`;
        echo $PYTHON;
    fi

  - pip install conan==1.11.1;
    pip install codecov;
    conan remote add piponazo https://api.bintray.com/conan/piponazo/piponazo;
    conan remote add kicer https://api.bintray.com/conan/kicer86/kicer;
    conan config set storage.path=~/conanData;

before_script:
  - if [ "$CC" = "gcc" ]; then
        export CXX=g++-7;
        export CC=gcc-7;
    else
        export CXX=clang++-5.0;
        export CC=clang-5.0;
    fi

  - conan profile new default --detect;
    cat ~/.conan/profiles/default;

  - GTEST_PATH=$TRAVIS_BUILD_DIR/usr/src/googletest

  # setup gmock and gtest
  - if [ ! -e $GTEST_PATH ]; then
        git clone https://github.com/google/googletest.git $GTEST_PATH;
    fi
  # photo broom
  - mkdir build && cd build
  - conan install .. --build
  - $CMAKE_BIN -DGTEST_DIR=$GTEST_PATH/googletest -DGMOCK_DIR=$GTEST_PATH/googlemock -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/usr -DBUILD_UPDATER=ON -DBUILD_TESTS=ON ..
  # start virtual frame buffer for gui unit DBUILD_TESTS  (https://docs.travis-ci.com/user/gui-and-headless-browsers/)
  - if [ $TRAVIS_OS_NAME == 'linux' ]; then
        export DISPLAY=:99.0;
        sh -e /etc/init.d/xvfb start;
    fi

script:
  - make
  - find -name core_tests_base
  - ctest -V
  - cat Testing/Temporary/LastTest.log
