sudo: required
dist: trusty

language: cpp

branches:
  only:
    - master
    - travis_test

notifications:
    on_failure: never
    on_success: never

matrix:
    include:
        # TODO: below env could be used as additional dimension in matrix but there is a feature missing:
        # https://github.com/travis-ci/travis-ci/issues/1519
        - compiler: gcc
          addons:
            apt:
             packages:
               - libboost-all-dev
               - g++-5
               - gcc-5
             sources:
               - ubuntu-toolchain-r-test
          # use compiler which has c++14 support
          env: COMPILER=g++-5 SHARED_BUILD=ON

        - compiler: gcc
          addons:
            apt:
             packages:
               - libboost-all-dev
               - g++-5
               - gcc-5
             sources:
               - ubuntu-toolchain-r-test
          # use compiler which has c++14 support
          env: COMPILER=g++-5 SHARED_BUILD=OFF

        - compiler: clang
          addons:
            apt:
             packages:
               - libboost-all-dev
               - clang-3.6
             sources:
               - ubuntu-toolchain-r-test
               - llvm-toolchain-precise-3.6
          # use compiler which has c++14 support
          env: COMPILER=clang++-3.6 SHARED_BUILD=ON

        - compiler: clang
          addons:
            apt:
             packages:
               - libboost-all-dev
               - clang-3.6
             sources:
               - ubuntu-toolchain-r-test
               - llvm-toolchain-precise-3.6
          # use compiler which has c++14 support
          env: COMPILER=clang++-3.6 SHARED_BUILD=OFF

before_install:
    # setup Qt 5.6 which is not in Ubuntu by default. To be removed in the future.
  - sudo add-apt-repository ppa:beineri/opt-qt561-trusty -y
  - sudo apt-get -qq update
  - sudo sudo apt-get install -qq qt56base qt56svg
  - source /opt/qt56/bin/qt56-env.sh

before_script:
  # third party stuff
  - mkdir build_third_party
  - pushd build_third_party
  - CXX=$COMPILER cmake -DBUILD_OPENLIBRARY=OFF -DBUILD_EASYEXIF=ON -DBUILD_JSONCPP=ON -DINSTALL_LOCATION=/usr ../cmake/third_party/
  - sudo make
  - popd
  # OL. For some unknown reason we cannot use script above to install OL - cmake cannot find Qt5Widgets.
  - mkdir build_ol && pushd build_ol
  - git clone git://github.com/Kicer86/openlibrary.git
  - cd openlibrary
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - make
  - sudo make install
  - popd
  # setup gmock and gtest
  - git clone https://github.com/google/googletest.git
  - GTEST_PATH=`pwd`/googletest
  # photo broom
  - mkdir build && cd build
  - CXX=$COMPILER cmake -DGTEST_DIR=$GTEST_PATH/googletest -DGMOCK_DIR=$GTEST_PATH/googlemock -DBUILD_TESTS=OFF -DBUILD_SHARED_LIBS=$SHARED_BUILD ..

script:
  - make
  - ctest -V
