
sudo: required
dist: trusty

language: cpp

branches:
  only:
    - master
    - travis_test

notifications:
    on_failure: never
    on_success: never

matrix:
    include:
        # TODO: below env could be used as additional dimension in matrix but there is a feature missing:
        # https://github.com/travis-ci/travis-ci/issues/1519
        - compiler: gcc
          addons:
            apt:
             packages:
               - g++-7
               - gcc-7
               - libexiv2-dev
               - python3
               - ninja
             sources:
               - ubuntu-toolchain-r-test
          # use compiler which has c++17 support
          env: COMPILER=g++-7 SHARED_BUILD=ON

        - compiler: gcc
          addons:
            apt:
             packages:
               - g++-7
               - gcc-7
               - libexiv2-dev
               - python3
               - ninja
             sources:
               - ubuntu-toolchain-r-test
          # use compiler which has c++17 support
          env: COMPILER=g++-7 SHARED_BUILD=OFF

        - compiler: clang
          addons:
            apt:
             packages:
               - libstdc++-7-dev
               - clang-5.0
               - libexiv2-dev
               - python3
               - ninja
             sources:
               - ubuntu-toolchain-r-test
               - llvm-toolchain-trusty-5.0
          # use compiler which has c++17 support
          env: COMPILER=clang++-5.0 SHARED_BUILD=ON

        - compiler: clang
          addons:
            apt:
             packages:
               - libstdc++-7-dev
               - clang-5.0
               - libexiv2-dev
               - python3
               - ninja
             sources:
               - ubuntu-toolchain-r-test
               - llvm-toolchain-trusty-5.0
          # use compiler which has c++17 support
          env: COMPILER=clang++-5.0 SHARED_BUILD=OFF

cache:
  directories:
  - $TRAVIS_BUILD_DIR/usr

before_install:
    # setup Qt 5.7 which is not in Ubuntu by default. To be removed in the future.
  - sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y
  - sudo apt-get -qq update
  - sudo sudo apt-get install -qq qt57base qt57svg
  - source /opt/qt57/bin/qt57-env.sh

before_script:
  # cmake (TODO: remove in the future)
  - wget https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.sh
  - chmod +x ./cmake-3.9.1-Linux-x86_64.sh
  - ./cmake-3.9.1-Linux-x86_64.sh --prefix=$TRAVIS_BUILD_DIR/usr --exclude-subdir --skip-license
  - export CMAKE_BIN=$TRAVIS_BUILD_DIR/usr/bin/cmake

  - GTEST_PATH=$TRAVIS_BUILD_DIR/usr/src/googletest
  # third party stuff
  - if [ ! -e $TRAVIS_BUILD_DIR/usr/lib ]; then
        pushd tools;
        python3 ./prepare_dependencies.py -p jsoncpp -p openlibrary $TRAVIS_BUILD_DIR/usr;
        popd;
    fi
  # setup gmock and gtest
  - if [ ! -e $GTEST_PATH ]; then
        git clone https://github.com/google/googletest.git $GTEST_PATH;
    fi
  # photo broom
  - mkdir build && cd build
  - CXX=$COMPILER $CMAKE_BIN -G Ninja -DGTEST_DIR=$GTEST_PATH/googletest -DGMOCK_DIR=$GTEST_PATH/googlemock -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/usr -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=$SHARED_BUILD ..

script:
  - make
  - ctest -V
