sudo: required
dist: trusty

language: cpp

branches:
  only:
    - travis_test

notifications:
    on_failure: never
    on_success: never
    
addons:
  apt:
    packages:
      - qtbase5-dev
    
before_script:
  # third party stuff
  - mkdir -p build/third_party
  - pushd build/third_party
  - cmake -DBUILD_OPENLIBRARY=TRUE ../../cmake/third_party/  
  - make
  - popd
  # photo broom
  - cd build
  - cmake .. -DCMAKE_PREFIX_PATH=third_party/install/lib/cmake/ -DOpenLibrary_DIR=third_party/install/lib/cmake/OpenLibrary -DEASYEXIF_LIBRARY=third_party/install/lib/libeasyexif.a -DEASYEXIF_INCLUDE_DIR=third_party/install/include


script: make
