
language: cpp
sudo: required
dist: bionic

branches:
  only:
    - master
    - travis_test

addons:
  apt:
    packages:
      - libexiv2-dev
      - qt510base
      - qt510svg
      - python3
      - g++-7
      - gcc-7
      - clang-5.0
      - lcov
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
      - sourceline: 'ppa:beineri/opt-qt-5.10.1-trusty'

  homebrew:
    packages:
      - qt5
      - exiv2
    update: true

notifications:
  on_failure: never
  on_success: never

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - DEBUG=0

matrix:
  exclude:
    - os: osx
      compiler: gcc
  include:
    - os: linux
      compiler: gcc
      env: DEBUG=1

  allow_failures:
    - os: osx

cache:
  directories:
    - $TRAVIS_BUILD_DIR/usr
    - $HOME/conanData           # Conan storage location
    - $HOME/tools               # tools like CMake
    - conan                     # Conan installation folder
    - /opt/python               # cache python installations

before_install:
  # setup tools for particular system
  - if [ $TRAVIS_OS_NAME == 'osx' ]; then
        brew upgrade pyenv;
        eval "$(pyenv init -)";
        export PATH="/usr/local/opt/qt/bin:$PATH"
        export CMAKE_BIN=cmake;
        export PYTHON=python;
        sudo pip install virtualenv;
        virtualenv conan;
        source conan/bin/activate;
    else
        CMAKE_VER=3.12;
        CMAKE_PATCH=4;
        source /opt/qt5*/bin/qt5*-env.sh;
        if [ ! -e $HOME/tools/bin/cmake ]; then
            wget https://cmake.org/files/v$CMAKE_VER/cmake-$CMAKE_VER.$CMAKE_PATCH-Linux-x86_64.sh;
            chmod +x ./cmake-$CMAKE_VER.$CMAKE_PATCH-Linux-x86_64.sh;
            ./cmake-$CMAKE_VER.$CMAKE_PATCH-Linux-x86_64.sh --prefix=$HOME/tools --exclude-subdir --skip-license;
        fi;
        export CMAKE_BIN=$HOME/tools/bin/cmake;
        export PYTHON=`which python`;
        echo $PYTHON;
    fi

  - pyenv install 3.6.0;
    pyenv global 3.6.0;
    pip install conan==1.11.1;
    pip install codecov;
    conan remote add piponazo https://api.bintray.com/conan/piponazo/piponazo;
    conan remote add kicer https://api.bintray.com/conan/kicer86/kicer;
    conan config set storage.path=$HOME/conanData;

before_script:
  - if [ "$CC" = "gcc" ]; then
        export CXX=g++-7;
        export CC=gcc-7;
    fi

  - if [ $DEBUG -eq 1 ]; then
        EXTRA_CMAKE_OPTIONS="-DENABLE_CODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug";
    fi

  - conan profile new default --detect;
    cat ~/.conan/profiles/default;

  - GTEST_PATH=$TRAVIS_BUILD_DIR/usr/src/googletest

  # setup gmock and gtest
  - if [ ! -e $GTEST_PATH ]; then
        git clone --branch release-1.8.1 --depth 1 https://github.com/google/googletest.git $GTEST_PATH;
    fi
  # photo broom
  - mkdir build && cd build
  - conan install .. --build
  - $CMAKE_BIN -DGTEST_DIR=$GTEST_PATH/googletest -DGMOCK_DIR=$GTEST_PATH/googlemock -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/usr -DBUILD_UPDATER=ON -DBUILD_TESTS=ON ${EXTRA_CMAKE_OPTIONS} ..
  # start virtual frame buffer for gui unit DBUILD_TESTS  (https://docs.travis-ci.com/user/gui-and-headless-browsers/)
  - if [ $TRAVIS_OS_NAME == 'linux' ]; then
        export DISPLAY=:99.0;
        sh -e /etc/init.d/xvfb start;
    fi

script:
  - make
  - ctest -V

after_success:
  - if [ $DEBUG -eq 1 ]; then
        cd ${TRAVIS_BUILD_DIR}/build;
        make run_unit_tests_code_coverage;
        lcov --directory . --capture --output-file coverage.info;
        lcov --remove coverage.info '/usr/*' --output-file coverage.info;
        lcov --list coverage.info;
        bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports";
    fi
