language: cpp

branches:
  only:
    - travis_test

before_install: 
    - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y  &&
      sudo apt-get update                                 &&
      sudo apt-get install qtbase5-dev
    
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
