sudo: required
dist: trusty

language: cpp

branches:
  only:
    - travis_test

notifications:
    on_failure: never
    on_success: never
    
addons:
  apt:
    packages:
      - qtbase5-dev
      - cmake cmake-data
    sources: &sources
      - ubuntu-sdk-team                     #qt5
      - george-edison55-precise-backports   #cmake
    
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
