sudo: required
dist: trusty

language: cpp

branches:
  only:
    - travis_test

notifications:
    on_failure: never
    on_success: never
    
addons:
  apt:
    packages:
      - qtbase5-dev
    
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
