
language: cpp
sudo: required
dist: trusty

branches:
  except:
    - appveyor

addons:
  apt:
    packages:
      - libexiv2-dev
      - qt57base
      - qt57svg
      - python3
      - g++-7
      - gcc-7
      - clang-5.0
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
      - sourceline: 'ppa:beineri/opt-qt571-trusty'

notifications:
  on_failure: never
  on_success: never

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
   - SHARED_BUILD=ON
   - SHARED_BUILD=OFF

matrix:
  exclude:
    - os: osx
      env: SHARED_BUILD=ON

  allow_failures:
    - os: osx

cache:
  directories:
    - $TRAVIS_BUILD_DIR/usr

before_install:
  # setup tools for particular system
  - if [ $TRAVIS_OS_NAME == 'osx' ]; then
        brew upgrade pyenv;
        brew install qt@5.7 exiv2;
        pyenv install 3.5.2;
        pyenv global 3.5.2;
        eval "$(pyenv init -)";
        export PATH="/usr/local/opt/qt@5.7/bin:$PATH"
        export CMAKE_BIN=cmake;
        export PYTHON=python;
    else
        pyenv install 3.6.0;
        pyenv global 3.6.0;
        source /opt/qt57/bin/qt57-env.sh;
        wget https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.sh;
        chmod +x ./cmake-3.9.1-Linux-x86_64.sh;
        ./cmake-3.9.1-Linux-x86_64.sh --prefix=$TRAVIS_BUILD_DIR/usr --exclude-subdir --skip-license;
        export CMAKE_BIN=$TRAVIS_BUILD_DIR/usr/bin/cmake;
        export PYTHON=`which python`;
        echo $PYTHON;
    fi

before_script:
  - if [ "$CC" = "gcc" ]; then
        export COMPILER=g++-7;
    else
        export COMPILER=clang++-5.0;
    fi

  - GTEST_PATH=$TRAVIS_BUILD_DIR/usr/src/googletest

  # third party stuff
  - if [ ! -e $TRAVIS_BUILD_DIR/usr/lib ]; then
        pushd tools;
        $PYTHON --version;
        $PYTHON ./prepare_dependencies.py -p jsoncpp -p openlibrary -p pybind11 $TRAVIS_BUILD_DIR/usr;
        popd;
    fi

  # setup gmock and gtest
  - if [ ! -e $GTEST_PATH ]; then
        git clone https://github.com/google/googletest.git $GTEST_PATH;
    fi
  # photo broom
  - mkdir build && cd build
  - CXX=$COMPILER $CMAKE_BIN -DGTEST_DIR=$GTEST_PATH/googletest -DGMOCK_DIR=$GTEST_PATH/googlemock -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/usr -DBUILD_UPDATER=ON -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=$SHARED_BUILD ..
  # start virtual frame buffer for gui unit DBUILD_TESTS  (https://docs.travis-ci.com/user/gui-and-headless-browsers/)
  - if [ $TRAVIS_OS_NAME == 'linux' ]; then
        export DISPLAY=:99.0;
        sh -e /etc/init.d/xvfb start;
    fi

script:
  - make
  - ctest -V
