
language: cpp
dist: bionic

branches:
  only:
    - master
    - travis_test

addons:
  apt:
    packages:
      - qt511base
      - qt511svg
      - python3
      - lcov
    sources:
      - ppa:beineri/opt-qt-5.11.1-bionic

  homebrew:
    packages:
      - qt5
      - exiv2
    update: true

notifications:
  on_failure: never
  on_success: never

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

services:
  - xvfb

env:
  - DEBUG=0

matrix:
  exclude:
    - os: osx
      compiler: gcc
  include:
    - os: linux
      compiler: gcc
      env: DEBUG=1

  allow_failures:
    - os: osx

cache:
  directories:
    - $TRAVIS_BUILD_DIR/usr
    - $HOME/conanData           # Conan storage location
    - $HOME/tools               # tools like CMake
    - conan                     # Conan installation folder

before_install:
  # setup tools for particular system
  - if [ $TRAVIS_OS_NAME == 'osx' ]; then
        brew upgrade pyenv;
        eval "$(pyenv init -)";
        export PATH="/usr/local/opt/qt/bin:$PATH"
        export CMAKE_BIN=cmake;
        export PYTHON=python;
        sudo pip install virtualenv;
        virtualenv conan;
        source conan/bin/activate;
    else
        sudo add-apt-repository -y ppa:beineri/opt-qt-5.11.1-bionic;
        sudo apt install qt511base qt511svg libgl-dev python3 lcov;
        source /opt/qt5*/bin/qt5*-env.sh;
        pyenv global 3.7.1;
        export PYTHON=`which python`;
        echo $PYTHON;
    fi

  - sudo pip install conan==1.11.1;
    conan remote add piponazo https://api.bintray.com/conan/piponazo/piponazo;
    conan remote add kicer https://api.bintray.com/conan/kicer86/kicer;
    conan config set storage.path=$HOME/conanData;

before_script:
  - if [ $DEBUG -eq 1 ]; then
        EXTRA_CMAKE_OPTIONS="-DENABLE_CODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug";
    fi

  - conan profile new default --detect;
    cat ~/.conan/profiles/default;

  - GTEST_PATH=$TRAVIS_BUILD_DIR/usr/src/googletest

  # setup gmock and gtest
  - if [ ! -e $GTEST_PATH ]; then
        git clone --branch release-1.8.1 --depth 1 https://github.com/google/googletest.git $GTEST_PATH;
    fi
  # photo broom
  - mkdir build && cd build
  - conan install .. --build
  - cmake -DGTEST_DIR=$GTEST_PATH/googletest -DGMOCK_DIR=$GTEST_PATH/googlemock -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/usr -DBUILD_UPDATER=ON -DBUILD_TESTS=ON ${EXTRA_CMAKE_OPTIONS} ..

script:
  - make
  - xvfb-run ctest -V

after_success:
  - if [ $DEBUG -eq 1 ]; then
        cd ${TRAVIS_BUILD_DIR}/build;
        make run_unit_tests_code_coverage;
        lcov --directory . --capture --output-file coverage.info;
        lcov --remove coverage.info '/usr/*' --output-file coverage.info;
        lcov --list coverage.info;
        bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports";
    fi
