
language: cpp
sudo: required
dist: trusty

branches:
  except:
    - appveyor

notifications:
    on_failure: never
    on_success: never

matrix:
    include:
        - os: osx
          osx_image: xcode9.2
          env: COMPILER=clang++-5.0 SHARED_BUILD=OFF

cache:
  directories:
  - $TRAVIS_BUILD_DIR/usr

before_install:
    # setup Qt 5.7 which is not in Ubuntu by default. To be removed in the future.
  - if [ $TRAVIS_OS_NAME == 'osx' ]; then
        echo;
    else
        sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y;
        sudo apt-get -qq update;
        sudo apt-get install -qq qt57base qt57svg;
        source /opt/qt57/bin/qt57-env.sh;
    fi

before_script:
  # cmake (TODO: remove in the future)
  - wget https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.sh
  - chmod +x ./cmake-3.9.1-Linux-x86_64.sh
  - ./cmake-3.9.1-Linux-x86_64.sh --prefix=$TRAVIS_BUILD_DIR/usr --exclude-subdir --skip-license
  - export CMAKE_BIN=$TRAVIS_BUILD_DIR/usr/bin/cmake

  - GTEST_PATH=$TRAVIS_BUILD_DIR/usr/src/googletest
  # third party stuff
  - if [ ! -e $TRAVIS_BUILD_DIR/usr/lib ]; then
        pushd tools;
        python3 ./prepare_dependencies.py -p jsoncpp -p openlibrary $TRAVIS_BUILD_DIR/usr;
        popd;
    fi
  # setup gmock and gtest
  - if [ ! -e $GTEST_PATH ]; then
        git clone https://github.com/google/googletest.git $GTEST_PATH;
    fi
  # photo broom
  - mkdir build && cd build
  - CXX=$COMPILER $CMAKE_BIN -GNinja -DGTEST_DIR=$GTEST_PATH/googletest -DGMOCK_DIR=$GTEST_PATH/googlemock -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/usr -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=$SHARED_BUILD ..
  # start virtual frame buffer for gui unit DBUILD_TESTS  (https://docs.travis-ci.com/user/gui-and-headless-browsers/)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - ninja
  - ctest -V
