sudo: required
dist: trusty

language: cpp

branches:
  only:
    - travis_test

notifications:
    on_failure: never
    on_success: never
    
addons:
  apt:
    packages:
      - libboost-all-dev
      - g++5
      - gcc-5
    sources:
      - ubuntu-toolchain-r-test
      
env: COMPILER=g++-5
    
before_install:
    # setup Qt 5.5 which is not in Ubuntu by default
  - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
  - sudo apt-get -qq update
  - sudo sudo apt-get install -qq qt55base qt55svg
  - source /opt/qt55/bin/qt55-env.sh
    
before_script:
  # third party stuff
  - mkdir build_third_party
  - pushd build_third_party
  - cmake -DBUILD_OPENLIBRARY=OFF -DBUILD_EASYEXIF=ON -DBUILD_JSONCPP=ON -DINSTALL_LOCATION=/usr ../cmake/third_party/  
  - sudo make
  - popd
  # OL
  - mkdir build_ol && pushd build_ol
  - git clone git://github.com/Kicer86/openlibrary.git
  - cd openlibrary
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - make
  - sudo make install
  - popd
  # photo broom
  - mkdir build && cd build
  - CC=gcc-5 CXX=g++-5 cmake ..

script: make
