
version: 1.1.{build}

branches:
  only:
    - master
    - appveyor

configuration:
    - Release
    - Debug

platform:
    - Win32
    - x64

cache:
    - c:\projects\install

befor_build:
    - call appveyor.bat

build:
  project: build/PhotoBroom.sln
  parallel: true
  verbosity: minimal
