
version: 1.2.{build}

branches:
  except:
    - travis_test

configuration:
    - Release
    - Debug

platform:
    #- Win32
    - x64

image: Visual Studio 2017

cache:
    - c:\projects\install      -> appveyor.bat, tools/prepare_dependencies.py
    - c:\projects\googletest   -> appveyor.bat, tools/prepare_dependencies.py
    - c:\program files\cmake   -> appveyor.bat, tools/prepare_dependencies.py

artifacts:
  - path: build/PhotoBroom-1.2.2-win64.exe
    name: PhotoBroom_installer

before_build:
    - git submodule update --init --recursive
    - call appveyor.bat

build:
  project: build/PhotoBroom.sln
  parallel: true
  verbosity: minimal

after_build:
    - if "%CONFIGURATION%" == "Release"  cmake --build . --target PACKAGE --config %configuration%
