
version: 1.2.{build}

branches:
  only:
    #- master
    - appveyor

configuration:
    - Release
    - Debug

platform:
    - Win32
    - x64

image: Visual Studio 2017

cache:
    - c:\projects\install      -> appveyor.yml, appveyor.bat
    - c:\projects\googletest   -> appveyor.yml, appveyor.bat
    - c:\program files\cmake   -> appveyor.yml, appveyor.bat

before_build:
    - call appveyor.bat

build:
  project: build/PhotoBroom.sln
  parallel: true
  verbosity: minimal
