
version: 1.2.{build}

branches:
  only:
    - master
    - appveyor

configuration:
    - Release
    - Debug

platform:
    - Win32
    - x64

cache:
    - c:\projects\install      -> appveyor.yml
    - c:\projects\googletest   -> appveyor.yml
    - c:\program files\cmake   -> appveyor.yml

before_build:
    - choco upgrade cmake
    - call appveyor.bat

build:
  project: build/PhotoBroom.sln
  parallel: true
  verbosity: minimal
